Разметка страницы каталога
htmlacademy-adaptive/1337987-cat-energy-21 pull request #4
Opened 2020-12-03 00:43 UTC by Flavissimo

1. БЭМ вложенность проверена (https://yoksel.github.io/html-tree/)
2. Код прошел проверку (https://validator.w3.org/nu)
3. Применила выравнивание

2020-12-03 06:25 UTC, 4err requested changes

2020-12-03 06:25 UTC, 4err commented on source/catalog.html
> +<html lang="en">
А почему английский? Заодно проверь и в индексе, возможно не заметил.

2020-12-03 06:25 UTC, 4err commented on source/catalog.html
> +      <section class="page-main__catalog-gallery production">
Для карточки товара лучше использовать `article` Это прям независимый элемент. А для самого списка товаров неплохо бы сделать `ul > li`

2020-12-03 06:25 UTC, 4err commented on source/catalog.html
> +      <button class="more-production__button" type="button" name="Открыть больше товаров">Показать все</button>
Ссылка же

2020-12-03 06:25 UTC, 4err commented on source/catalog.html
> +        <div class="additional-products__list">
А для чего вообще эта обертка?

2020-12-04 18:27 UTC, Flavissimo commented
1. Все замечания исправила.
2. Выровняла.
3. Код прошел проверку Бэм вложенности.

2020-12-05 07:19 UTC, merged